version: '3.7'
services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
  app: 
    depends_on:
      - mongodb
    build: .
    ports:
      - 3000:3000
    stdin_open: true
    tty: true

volumes:
  db: